jobs:
 - name: daily
   targetName: dev
   schedule: 0 12 * * *
   steps:
     - name: run models
       command: dbt run
     - name: test models
       command: dbt test

 - name: nightly
   schedule: 0 0 * * *
   steps:
     - name: run models
       command: dbt run

